### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by ljmna** [konturio/geocint-runner#8]
Structure the project so that the three repositories are contained within one folder and fix the config variables and relative paths to work without requiring /home/user location

**Comment by ljmna** [comment]
Remove SUDO from pip installs

**Comment by ljmna** [comment]
older than required versions of cmake are downloaded in the script

**Comment by ljmna** [comment]
Start script throws error E: Unable to locate package libgdal30

**Comment by Zkir** [comment]
Done. Now repositories can be located in any folder, as specified in pipeline configuration file: config.inc.sh
